export const mockDeliveries = [
  {
    id: '1',
    clientName: 'Ben Njoki',
    clientType: 'Restaurant Owner',
    location: 'Nairobi',
    price: 43,
    status: 'pending',
    date: 'April 2025',
    time: '09:34',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: -1.2647,
      longitude: 36.8106,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: -1.2921,
      longitude: 36.8219,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
  {
    id: '2',
    clientName: 'Mary Kamau',
    clientType: 'Retail Store',
    location: 'Mombasa',
    price: 29,
    status: 'pending',
    date: '03 April',
    time: '10:24',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: -4.0619,
      longitude: 39.6682,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: -4.0435,
      longitude: 39.6682,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
  {
    id: '3',
    clientName: 'John Omondi',
    clientType: 'Pharmacy',
    location: 'Kisumu',
    price: 36,
    status: 'ongoing',
    date: '03 April',
    time: '08:54',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: -0.0857,
      longitude: 34.7732,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: -0.0917,
      longitude: 34.7680,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
  {
    id: '4',
    clientName: 'Sarah Njeri',
    clientType: 'Bookstore',
    location: 'Nakuru',
    price: 19,
    status: 'ongoing',
    date: '03 April',
    time: '09:34',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: -0.2827,
      longitude: 36.0800,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: -0.3031,
      longitude: 36.0800,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
  {
    id: '5',
    clientName: 'Daniel Kiprop',
    clientType: 'Electronics Shop',
    location: 'Eldoret',
    price: 65,
    status: 'completed',
    date: '02 April',
    time: '10:24',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: 0.5200,
      longitude: 35.2697,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: 0.5143,
      longitude: 35.2395,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
  {
    id: '6',
    clientName: 'Elizabeth Wanjiku',
    clientType: 'Fashion Boutique',
    location: 'Thika',
    price: 52,
    status: 'completed',
    date: '01 April',
    time: '14:12',
    from: 'Impala Club',
    to: 'The Village Market',
    pickupCord: {
      latitude: -1.0332,
      longitude: 37.0690,
      latitudeDelta: 0.0422,
      longitudeDelta: 0.0421,
    },
    dropoffCord: {
      latitude: -1.0395,
      longitude: 37.0800,
      latitudeDelta: 0.0440,
      longitudeDelta: 0.0421,
    },
  },
];

export const mockChats = [
  {
    id: '1',
    name: 'Ben Njoki',
    avatar: 'https://i.ibb.co/M8JnWhy/avatar.png',
    lastMessage: 'Hello, I wanted to confirm if my package will arrive today.',
    lastMessageTime: '10:42 AM',
    unreadCount: 2,
    read: false,
    online: true,
  },
  {
    id: '2',
    name: 'Mary Kamau',
    avatar: 'https://i.ibb.co/YP0NDzM/avatar-2.png',
    lastMessage: 'Thank you for the quick delivery!',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    read: true,
    online: false,
  },
  {
    id: '3',
    name: 'John Omondi',
    avatar: 'https://i.ibb.co/VVxS579/avatar-3.png',
    lastMessage: 'Is the estimated delivery time still 2PM?',
    lastMessageTime: 'Yesterday',
    unreadCount: 1,
    read: false,
    online: true,
  },
  {
    id: '4',
    name: 'Sarah Njeri',
    avatar: 'https://i.ibb.co/Lptzj15/avatar-4.png',
    lastMessage: 'Please call me when you arrive.',
    lastMessageTime: '2 days ago',
    unreadCount: 0,
    read: true,
    online: false,
  },
  {
    id: '5',
    name: 'Daniel Kiprop',
    avatar: 'https://i.ibb.co/hM0WPBH/avatar-5.png',
    lastMessage: 'I need to change the delivery address.',
    lastMessageTime: '3 days ago',
    unreadCount: 0,
    read: true,
    online: false,
  },
];